sudo: required
services:
  - docker
language: python
python:
- 3.6
cache:
  apt: true
  pip: true
  directories:
    - "$HOME/google-cloud-sdk/"
env:
  global:
    - "QUAY_USERNAME=economic+vml_rw"
    - secure: "WDFFUIBHA6pSO7H+G/4UrL2qIzmIYmIjGrWPytCLdpovIeXlsmWEgrOZ1FaS0QPiWefaryxhWwj+ghrCpzA2dBanE7fEC0nYMRGr6N/0D0qe65CXrrmHodIz3GlFHKUdsfQ+dgPjMlLNYjRMm3hhylL33lQM5S1/14M/NKgR6GotbSeZtqfXTBP7ljbIGkIocpaU3MZ6PCH9I/o49sZruWdP8J/StR5ION3LQqdNaF2/4jMFgS+sGJApnz214gACkujoDUhib/yv+N1a691LxR6l81GIsyUdsDDFHhT+bFNeIkvnE+1IIy7i4yN0wxfqBze2cX5GvGQEzHxz+lhjGLmfuIKJ/1axEkO8k02Eqet5HesRIsIWJu/ab6oGrkbBjoNe45jciYZQ7rBAOyrzHS5B9jwRxgAT69GF1nwN6BU3wWyFiOVGZC9gks2pNPXziMJCclNY/GjNdwhu5lSBPaaWjiW04o+fdxn2L4+AgOPtiHjdkfeQs7GYSKcTZa3freqkO/IxnIWeaRhqhEEO1mSFP66/+owS+sNEnJrjfaXc73kWE2uwQgWSnJTO61UXe83/Y9ZIETuneewEbwynNlj1rrQ9odS1XkRNlGCCvf0kc8hFBxr98+YOuiUH2qFeFWK/Qxg6xHZDaa3CJAHEtceIUdXIzRx/ZO2noMNNF7o="
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- pip install --upgrade pip setuptools
install:
- pip install -r requirements.txt
script:
- mkdocs build
before_deploy:
- echo $QUAY_PASSWORD | docker login -u $QUAY_USERNAME --password-stdin quay.io
- docker build -t economic/vml-docs .
- docker tag economic/vml-docs quay.io/economic/vml-docs:latest
- docker tag economic/vml-docs quay.io/economic/vml-docs:$TRAVIS_BUILD_NUMBER
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud --quiet components update kubectl
# Auth flow
- echo $GCLOUD_KEY | base64 --decode > gcloud.p12
- gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
deploy:
  - provider: script
    script: docker push quay.io/economic/vml-docs:latest &&
            docker push quay.io/economic/vml-docs:$TRAVIS_BUILD_NUMBER
    on:
      branch: master
  - provider: script
    script: gsutil rsync -r site gs://vml-docs
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
