site_name: VML Docs
nav:
  - Getting Started: index.md
  - Smartscan: smartscan.md
  - Autosuggest: autosuggest.md
  - Autosuggest 2.0: autosuggest2.md
  - New Autosuggest 2.0: autosuggest2new.md
  - Support: support.md
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: false
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.tasklist
  - markdown.extensions.attr_list:

plugins:
  - render_swagger

extra_css:
  - stylesheets/extra.css
  - stylesheets/swagger-ui-base.css
  - stylesheets/swagger-ui.css

extra_javascript:
  - scripts/swagger-ui.js